global:
  uniqueSystemDeviceNames: false

server:
  publicHostname: "10.10.1.118"
  ipv6: false
  lanMode: false

devices:
- id: "FT710"
  type: "rigctld"
  rigctld:
    localInstance:
      enabled: true
      model: 1049
      rigDevice: "id:usb-Silicon_Labs_CP2105_Dual_USB_to_UART_Bridge_Controller_01B9C937-if00-port0"
      serialSpeed: 38400

  media:
    stream:
      audioInputDeviceName: "alsa_input.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.mono-fallback"
      audioOutputDeviceName: "alsa_output.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.analog-stereo"